apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: fund-transfer
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS fund_transfer_db;
    USE fund_transfer_db;

    CREATE TABLE IF NOT EXISTS transactions (
                                              id INT AUTO_INCREMENT PRIMARY KEY,
                                              service VARCHAR(100) NOT NULL,
      name VARCHAR(100),
      amount VARCHAR(100) NOT NULL,
      account VARCHAR(100) NOT NULL,
      reference VARCHAR(100) UNIQUE NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );

    CREATE INDEX idx_transactions ON transactions (id, reference);
