apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fund-transfer-api-logs-pvc
  namespace: fund-transfer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
