apiVersion: v1
kind: Service
metadata:
  name: fund-transfer-api-service
  namespace: fund-transfer
  labels:
    app: fund-transfer-api
spec:
  selector:
    app: fund-transfer-api
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: LoadBalancer

#apiVersion: v1
#kind: Service
#metadata:
#  name: fund-transfer-api-service
#  namespace: fund-transfer
#  labels:
#    app: fund-transfer-api
#spec:
#  selector:
#    app: fund-transfer-api
#  ports:
#    - protocol: TCP
#      port: 8765
#      targetPort: 8765
#      nodePort: 30080
#  type: NodePort
