#name: Package
#
#on:
#  push:
#    paths:
#      - "src/**"
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      # Checkout the repository
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Set up JDK 21
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      # Cache Maven dependencies
#      - name: Cache Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      # Build the project
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Push Docker Image
#        id: docker_build
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64,linux/arm64
#          tags: charity1475/fund-transfer-api:latest
#          push: true
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
